name: ffbah_example

workspace:
  - server
  - app

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

buildpack:
  server: server
  static: app
  prebuild: |
    echo "prebuild flutter!"
  postbuild: |
    echo "post build flutter!"
